### PR TITLE
Refactored the mocketize decorator

### PR DESCRIPTION
**Pull request by micheles**
This is how the decorator module should be used. Not all tests pass on my machine but I guess I am missing some infrastructure and the problem has nothing to do with my change.

### CODE REVIEW

**Comment by mindflayer** [comment]
Someone has just opened [this issue](https://github.com/kiwi-bop/kiwi-back/pull/1778) and it looks like the same issue that makes your tests failing.
I'll have a look at it then I'll merge this PR.
Thanks for the refactor, I like it.

**Comment by mindflayer** [comment]
@micheles do you mind merging from `master`?

**Comment by mindflayer** [comment]
I tried to apply your changes to `master` in this PR and tests are still failing, even if I solved the issue related to `urllib3`.

https://github.com/mindflayer/python-mocket/pull/153

**Comment by mindflayer** [comment]
Here you can see that now `master` is able to run all the tests without pinning `urllib3`:
https://github.com/mindflayer/python-mocket/actions/runs/925082757

**Comment by mindflayer** [comment]
I'll try to fix the PR where I applied the patch from yours. I believe it's something related to the your changes which broke the `AsyncMocketizer`.

**Comment by micheles** [comment]
I have no time to look at this now. Let's keep the status quo.

**Pull request closed without merging**
