### PR TITLE
Support for Python 3.11

### PR DESCRIPTION
**Pull request by mindflayer**
- Migrating the HTTP[S] mock from relying on `http-parser` to `httptools`.
- Never discovered the root cause for the failing tests with `aiohttp`/Python 3.11 (first time ever I added `@pytest.mark.xfail` to a test). Same test works with `httpx`, so I suspect it's related to a client issue. I'll probably migrate to `httpx` as the one for testing `async/await` code.

### CODE REVIEW

**Comment by amotl** [comment]
Hi there,

aiming to add support for Python 3.11 to the [Terkin Datalogger](https://github.com/hiveeyes/terkin-datalogger), we had to downgrade to `mocket<3.9` (see https://github.com/hiveeyes/terkin-datalogger/commit/3b8a94bb0), in order to make it work on Python 3.11.

It looks like `http-parser` is not ready for Python 3.11 yet.

With kind regards,
Andreas.

**Comment by mindflayer** [comment]
Hi Andreas,
I'm aware of it and keeping an eye on their repo.
There is already an issue with the fix but it hasn't been merged yet.
I was planning to write to the author in case it won't be taken care of
soon.

Regards,
Giorgio

**Comment by amotl** [comment]
Thank you! I've added a comment to https://github.com/benoitc/http-parser/pull/95, and exercised the upgrade to Python 3.11 and `mocket-3.9.x` on behalf of https://github.com/hiveeyes/terkin-datalogger/pull/116.

**Comment by amotl** [comment]
Hi again,

> [...] we had to downgrade to `mocket<3.9` (see https://github.com/hiveeyes/terkin-datalogger/commit/3b8a94bb0), in order to make it work on Python 3.11.

With https://github.com/hiveeyes/terkin-datalogger/commit/ffcffbaa26, the test suite now uses a modern version of Mocket for all Python versions <3.11, while still resorting to `mocket<3.9` on Python 3.11.

We know it is not an optimal solution, and this release probably lacks many features, but it was enough to satisfy our test suite, and it might help others as well.

With kind regards,
Andreas.

**Comment by mindflayer** [comment]
Hi @amotl, I replaced `http-parser` with the modern `httptools`, but some tests are failing on Python 3.11. I'll do my best to try to close this PR as soon as possible. Feel free to have a look at them, in case you have some time for it.

**Comment by amotl** [comment]
Hi @mindflayer,

thanks for sharing those news. I had a look at the exception message `aiohttp.client_exceptions.ClientOSError: Cannot write to closing transport`, but the code at this place is not trivial, so I could not figure it out.

Maybe those discussions have some hints about that exception?
- https://github.com/aio-libs/aiohttp/issues/4587
- https://github.com/aio-libs/aiohttp/pull/4778

With kind regards,
Andreas.

[^1]: https://github.com/mindflayer/python-mocket/actions/runs/3687114724/jobs/6240275161#step:6:605

**Pull request merged**
