### PR TITLE
Allow specifying strict mode exceptions

### PR DESCRIPTION
**Pull request by ento**
I'm trying to use a library that sends test stats to a remote server in the background, and tests that use Mocket in strict mode would fail intermittently when the library tries to make an HTTP request.

This PR adds a new `strict_mode_allowed: list[str | tuple[str, int]]` parameter to `Mocketizer`, which specifies which host or host and port can be made requests against even in strict mode.

Suggestions for a better name for the parameter would be welcome, if any. What some other libraries use...
- [HTTPretty's unmerged PR](https://github.com/gabrielfalcao/HTTPretty/pull/448/files): `whitelist`
- [WebMock, a Ruby library](https://github.com/bblimke/webmock#external-requests-can-be-disabled-while-allowing-specific-requests): `allow`

### CODE REVIEW

**Comment by mindflayer** [comment]
Hi @ento, thanks for contributing to Mocket.

Would would be the use-case for adding exceptions to Strict Mode, this feature is suppose to check if your mock continues working as expected.
Could we please discuss it in an issue before talking about code itself?

**Comment by ento** [comment]
Opened an issue: #218

**Comment by mindflayer** [comment]
Amazing work, thank you very much. I'll start working on it soon.

**Comment by ento** [comment]
Thanks! I appreciate how mocket is well-maintained.

**Pull request merged**
