### PR TITLE
Refactor split socket and ssl socket

### PR DESCRIPTION
**Pull request by betaboon**
continuation of #261 #262 #263 #264 

This PR includes the following changes:
- extend `FakeSSLContext` by replacing all dummy-methods with full signatures
- move `FakeSSLContext` from `mocket.ssl` to `mocket.ssl.context`
- move all mock- and true-functions from `mocket.inject` to `mocket.socket` and `mocket.ssl.context`
- type all function signatures of `MocketSocket` 
- split ssl-specific methods from `MocketSocket` into `MocketSSLSocket`

Some notes:

`socket.read` and `socket.write` seem to have been considered part of the `socket`-api.
They are infact part of `SSLSocket` and have thus been incorrectly used.
a test and some smaller internal methods had to be changed accordingly.

### CODE REVIEW

**Comment by betaboon** [comment]
interesting. i tested locally with python3.8, which passes.
with 3.11 i can reproduce the tests failing. will look at that tomorrow

**Comment by betaboon** [comment]
hey. in my eyes it contributes to readability.

but again, preferences. if you prefer the less-verbose way, i will revert :)

**Comment by mindflayer** [comment]
I am not sure that having x lines of copy/pasted functions is more readable than having a single catch-all method.

**Comment by betaboon** [comment]
> Weren't you the one who split the logic into two separated classes: `MocketSocket` AND `MocketSSLSocket`?

yep. exactly for the reason of cleanly separate the apis.

eg this in the tests is just wrong:
```python 
       sock = socket.socket()
        sock.connect(address[-1])
        sock.write(f"{method} {path} HTTP/1.0\r\n")
```
`socket.socket` does not have a `write`-method.

**Comment by mindflayer** [comment]
> yep. exactly for the reason of cleanly separate the apis.
> 
> eg this in the tests is just wrong:

Yes, the test was using the wrong method. It was added by a contributor and I did not spot the fact that it was using `write()`. Good catch!

**Comment by betaboon** [comment]
from my perspective this is ready.

**Comment by mindflayer** [comment]
> from my perspective this is ready.

I am working atm, I'll review it as soon as possible.

**Comment by betaboon** [comment]
take your time. I'm back at work too :)

**Review by mindflayer — APPROVED** [review]
LGTM!

**Pull request merged**
